#!/bin/bash

#Write a script which updates all the package sources, then all the packages, and then
#logs everything in a file named /var/log/update_script.log. Create a scheduled
#task for this script, once per week at 4 AM.


# insert in crontab -e
# 0 4 * * 1 /bin/bash /path/to/script/
apt-get update >> /var/log/update_script.log
apt-get upgrade -y >> /var/log/update_script.log
