#!/bin/bash

#Write a script which monitors the modifications made to the /etc/crontab file and
#sends an e-mail to root if the file is modified. Create a scheduled task to run this
#script everyday at midnight


if [ ! -f $HOME/crontab.md5  ]
then
	md5sum /etc/crontab > $HOME/crontab.md5
elif ! md5sum -c $HOME/crontab.md5
then
	echo "/etc/crontab changed" | mail -s "/etc/crontab was changed !!!!!" root
	md5sum /etc/crontab > $HOME/crontab.md5
fi

# From create scheduled task to run script, add : "0 0 * * * root /path/to/script" to /etc/crontab
